services:
  app:
    build: .
    container_name: bildyapp-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      DB_URI: mongodb://mongo:27017/bildyapp
      JWT_SECRET: 
      JWT_REFRESH_SECRET: 
      JWT_EXPIRES_IN: 2h
      JWT_REFRESH_EXPIRES_IN: 7d
      CLIENT_URL: "*"
      CLOUDINARY_CLOUD_NAME: 
      CLOUDINARY_API_KEY: 
      CLOUDINARY_API_SECRET: 
      MAIL_HOST: 
      MAIL_PORT: 
      MAIL_USER: 
      MAIL_PASS: 
      MAIL_FROM: 
      SLACK_WEBHOOK_URL: 
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: bildyapp-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: